react-native-device-info/react-native-device-info

- RNDeviceInfo.podspec
- package.json
You can start using cocoapods.
In your podfile you should write
pod 'RNDeviceInfo', :path => 'node_modules/react-native-device-info-pod'
> Add podspec file.

- README.md
- RNDeviceInfo/RNDeviceInfo.m
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- deviceinfo.js
- package.json
Add device locale to the constants offered by the package.
> Device locale

- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
As discussed in #14.
I didn't change much code, tell me if there is something more I can do!
> Use getLanguageTag to retrieve device locale

- README.md
I made some small changes to the README to make the installation process a bit easier.
> Small updates to README.md to make install easier

- README.md
Cocoa pods installation instructions.
> Update README.md w/ cocoapods installation instructions

- .gitignore
- README.md
- android/build.gradle
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- deviceinfo.js
Adding support for android's Instance ID
I apologize, I tried to squash my commits by rebasing, but I'm new to it and clearly did something wrong... ended up adding more commits :-(.  If you can't merge due to this, no worries..
> Adding support for android's Instance ID

- README.md
should be good now, we can lower this flag.
> plenty of maintainers now

- RNDeviceInfo/RNDeviceInfo.m
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
I apologize if the iOS version doesn't "just work"; my Objective C knowledge is very minimal right now and I'm blind coding.
> Add timezone

- README.md
Add instruction of installing via `rnpm`
> Install with rnpm

- README.md
> Update README.md (small typo)

- README.md
RN moved the getPackages method from MainActivity to MainApplication in 0.29
> Fix instructions for android

- RNDeviceInfo.xcodeproj/project.pbxproj
- RNDeviceInfo/DeviceUID.h
- RNDeviceInfo/DeviceUID.m
- RNDeviceInfo/RNDeviceInfo.m
Primarily taken from https://gist.github.com/miguelcma/e8f291e54b025815ca46 with several small changes to make it work (that script crashes). 
This needs "added" to the iOS project but I don't have a Mac at home. I can guarantee it works and passes iOS review as we're using it in production.
> Use persistent UID for iOS

- CHANGELOG.md
- README.md
> improve README

- android/build.gradle
> don't pin gradle dependency versions

- RNDeviceInfo/RNDeviceInfo.m
> Avoid crash when country code is nil

- README.md
- deviceinfo.js
fixes #73 
and corrects 2 typos in README
> Add getTimezone() in JS

- RNDeviceInfo/RNDeviceInfo.m
https://en.wikipedia.org/wiki/List_of_iOS_devices
> add iPhone 7 & iPhone 7 Plus to deviceName

- README.md
- RNDeviceInfo/RNDeviceInfo.m
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- deviceinfo.js
detect code is running in the Simulator
> detect device is Simulator?

- README.md
- RNDeviceInfo/RNDeviceInfo.m
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- deviceinfo.js
Detects whether you're on a tablet device when using iOS or Android. Inspired by PR #92, but addresses @GantMan's concerns with it.
> added isTablet method for iOS and Android

- android/build.gradle
Need to update this in order to use with the latest build tools
> Update buildToolsVersion to 25.0.1

- README.md
You had two Device Names in here, which was a little confusing. Changed to use System Name and System Version.
> Use System for System.

- RNDeviceInfo.xcodeproj/project.pbxproj
- RNDeviceInfo/RNDeviceInfo.h
Keep compatibility with older versions of RN
> Compatible with old versions of react native

- deviceinfo.d.ts
- package.json
> Typescript support

- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceInfo.java
https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
> Handle Android RN 0.47 breaking change

- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Before this change the userAgent lacks the Chrome Version on Android:
"Dalvik/1.6.0 (Linux; U; Android 4.4.2; SM-T230 Build/KOT49H)"
After this change:
"Mozilla/5.0 (Linux; Android 4.4.2; SM-T230 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36"
> Get real WebView UserAgent on Android

- README.md
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- deviceinfo.js
Adds ability to grab the phone number of the device in Android.
> Add support for phone number.

- README.md
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceInfo.java
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- deviceinfo.d.ts
- deviceinfo.js
Add firstInstallTime and lastUpdateTime from Android PackageInfo
> First and Last Install Time

- RNDeviceInfo.xcodeproj/project.pbxproj
- RNDeviceInfo/RNDeviceInfo.m
Created a tvOS build target, and removed the use of `UIWebView` on Apple TV.
> Add tvOS support

- CHANGELOG.md
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
getCurrentActivity() occasionally returns null
> Check for null with getCurrentActivity()

- CHANGELOG.md
Keeping that changelog rolling now.
> changelog update :pen:

- RNDeviceInfo/RNDeviceInfo.m
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- deviceinfo.d.ts
- deviceinfo.js
- deviceinfo.js.flow
- package.json
- windows/RNDeviceInfo/RNDeviceInfoModule.cs
Verified on Android and iOS.
I don't have an environment to test Windows.
> Add 24 hour detection

- RNDeviceInfo/RNDeviceInfo.m
> Remove LocalAuthentication import on tvOS

- CODE_OF_CONDUCT.md
Rebecca, Gant,
If it's okay with you, I would like to add this COC in the repo. 
I wrote down my email as contact information.
Let me know if I can merge this, thanks!
> docs: add COC based on the Contributor Covenant

- CHANGELOG.md
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixed issue #320 
* [X ] I have tested this on a device/simulator for each compatible OS
* [X ] I mentioned this change in `CHANGELOG.md`.
> fix: safe guard getFreeDiskStorage() and getTotalDiskCapacity()

- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
> fix(android): fix Android > 6 compatibility for getMacAddress()

- CHANGELOG.md
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixed issue #425
| iOS     |    NO CHANGE     |
| Windows |    NO CHANGE     |
* No needed
> Support deprecated accessing locale directly on Android

- deviceinfo.js
Fixed issue #403
N/A
I don't believe this fix needs to be mentioned anywhere
> #403: Fix eslint-plugin-import error

- ios/RNDeviceInfo/RNDeviceInfo.m
Fixes #493 and replaces PR #495
> feat: Support new models (XR, XS, XS Max) and iPad 6th Gen

- README.md
- deviceinfo.d.ts
- deviceinfo.js
- deviceinfo.js.flow
Fixed issue #427 
Added hasNotch() that returns a boolean if the device has a notch.
> Add hasNotch()

- CHANGELOG.md
- README.md
- deviceinfo.d.ts
- deviceinfo.js
- deviceinfo.js.flow
- web/index.js
Added `isLandscape()`
* [✅] I have tested this on a device/simulator for each compatible OS
* [✅] I added the documentation in `README.md`.
* [✅] I mentioned this change in `CHANGELOG.md`.
> Added isLandscape data

- deviceinfo.js
Append Xiaomi Notch Devices in notch list.
> Append xiaomi notch info

- deviceinfo.js
Added OnePlus 6 (India Version) in Devices with notch list.
> Updated Devices with Notch List

- deviceinfo.js
There are different models available for the oneplus 6
Note that the capital letters are needed, since we dont lowercase strings before comparison
I will create a separate PR for lowercase comparison
> add-new-model

- deviceinfo.js
added OnePlus 6T to the notch devices
> added Oneplus 6T

- README.md
> docs(README.ms): Add missing double quote

- deviceinfo.js
> Fixes #568

- deviceinfo.js
Fix hasNotch() support for LG phones 
| Android |    ✅  |
> Update deviceinfo.js, Fix hasNotch() support for LG phones

- README.md
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- deviceinfo.d.ts
- deviceinfo.js
- deviceinfo.js.flow
Added `isAutoDateAndTime()` that allows user to verify whether the automatic time and date option is eneabled.
Added `isAutoTimeZone()` that allows user to verify whether the automatic time zone option is enabled.
> [PS] Added isAutoDateAndTime and isAutoTimeZone function

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/issue_template.md
- CHANGELOG.md
- README.md
- RNDeviceInfo.podspec
- package.json
Since this project transferred from https://github.com/rebeccahughes/react-native-device-info we should update url accordingly
I check all the url that i changed and verify all links are valid with no direct
> chore: Update url to react-native-community

- deviceinfo.js
Such a rare phone. But my colleague has one. Support the minority 🎉
> Add Nokia 7.1 to devicesWithNotch list

- example/.flowconfig
- example/__tests__/App-test.js
- example/android/app/build.gradle
- example/android/app/src/debug/AndroidManifest.xml
- example/android/app/src/main/AndroidManifest.xml
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/babel.config.js
- example/index.js
- example/ios/example.xcodeproj/project.pbxproj
- example/ios/example/AppDelegate.h
- example/ios/example/AppDelegate.m
- example/metro.config.js
- example/package-lock.json
- example/package.json
- refresh-example.sh
The example isn't shipped with the module so I don't think it needs a changelog entry, it's basically a gigantic programmatic piece of documentation
I made a couple tiny changes to the refresh script, then the rest is just the result of running it
I'll let this sit for a couple days for consideration and in the absence of disagreement, I'll merge it in
> chore: Refresh example to react-native@0.59.2 + react-native-device-info@master

- CHANGELOG.md
- README.md
I think the section I added should address the issue, as noted in [the comment](https://github.com/react-native-community/react-native-device-info/issues/586#issuecomment-476945422). There was no dissent there as of yet. I'll let this sit for a bit, then merge it in
> chore: update README troubleshooting to provide guidance for #586

- MAINTAINERS.md
@machour here is another quick docs one for you - I tried to write down everything I remembered about the exact processes (enough to stumble through them) as well as some friendly advice for future people? Did I make any mistakes? forget anything vital?
> docs: add maintainers information describing current processes

- example/README.md
- example/ios/Podfile
- example/ios/example.xcodeproj/project.pbxproj
- example/package-lock.json
- example/package.json
- refresh-example.sh
#615 indicates we need better Pod documentation
I added a Podfile to the example, tested it worked, and added it to the example doc
> docs: add Podfile and README to example, refresh example

- deviceinfo.js
Added Huawei INE_LX1 to devices with notch list.
| Windows |    ✅    |
> Add Huweai INE-LX1 to devices with notch

- README.md
Added Contributing section in Readme for easy access.
> Updated Readme with Contributing section

- CHANGELOG.md
- deviceinfo.js
Fixed issue #633
Append Xiaomi Mi at Lite in notch list.
> Fixed issue #633 & add Xiaomi Mi A2 Lite to Notch list

- deviceinfo.js
Fixed issue hasNotch() return false on Xiaomi Mi 8 Lite, fix devicesWithNotch config with `DeviceInfo.getModel()`
> chore: Update deviceinfo.js entry for xioami mi 8 lite

- CHANGELOG.md
- README.md
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- default/index.js
- deviceinfo.d.ts
- deviceinfo.js
- deviceinfo.js.flow
- example/App.js
Added `hasSystemFeature(feature: string)` that allows to check whether a specific system feature is available for Android devices.
> feat: implement hasSystemFeature() method for Android devices

- README.md
Podspec name has fixed in Troubleshooting -> ios podfile example section.
> Update README.md to have correct Podspec name

- README.md
Updated automatic linking which requires extra step in case of IOS, helps fix #353
Fixed issue #353
| iOS     |    ✅ |
* [ ✅ ] I added the documentation in `README.md`
> Updated Readme.md - include pod install note post-link

- CHANGELOG.md
- deviceinfo.js
Fixed issue #681
Added `Redmi Note 7` to `devicesWithNotch`
> fix: add Xiaomi Redmi Note 7 to devices with notch

- deviceinfo.js
* Added some devices that have notches to the list of devices with notches.
> fix: add missing devices to devices with notch list

- README.md
Fixed issue #706
*It doesn't fit the template because the only change in Readme file*
> docs(README): Add detail to ios getUniqueID() docs

- README.md
Fixed issue "Wrong example result of getBrand() in README.md"
Changed 'Xiaomi' to 'xiaomi'. (this might get confused)
| iOS       |    ✅     |
> Wrong example result of getBrand() in README.md

- deviceinfo.js
Fixed issue #709
| iOS     |     ❌      |
| Android |     ✅      |
| Windows |     ❌      |
> Add Huawei P30 to devices with notch list

- README.md
> fix wording mistake

- ios/RNDeviceInfo/RNDeviceInfo.m
Async `getUserAgent` method that uses `WKWebView`. Highly inspired by https://github.com/expo/expo/blob/master/packages/expo-constants/ios/EXConstants/EXConstants.m. Expo is actually better because they save the value and don't create WebView again. 
#756
> async user agent usinc WKWebView

- README.md
> Info for #748

- windows/RNDeviceInfo/RNDeviceInfoModule.cs
Fixes various build errors for the windows version of the package
> Various fixes for the windows version

- CHANGELOG.md
- deviceinfo.js
| Android |    NA     |
| Windows |    NA     |
* [x ] I have tested this on a device/simulator for each compatible OS
* [na?] I added the documentation in `README.md`
* [x ] I mentioned this change in `CHANGELOG.md`
* [na?] I updated the typings files (`deviceinfo.d.ts`, `deviceinfo.js.flow`)
* [ na?] I updated the dummy web/test polyfill (`default/index.js`)
* [ na?] I added a sample use of the API (`example/App.js`)
> Added 2019 iPhone model names for 'hasNotch' functionality

- README.md
Added punctuation, as the text wraps when rendered as is, and not having punctuation is confusing.  Added quoting.
> Minor updates to the docs for getUniqueId()

- README.md
> fixes #806

- CHANGELOG.md
- ios/RNDeviceInfo/RNDeviceInfo.m
> Support wifi IP address on Apple TV

- src/internal/devicesWithNotch.ts
Fixed hasNotch issue for Nokia 6.1 Plus device
> Fixed hasNotch issue in nokia 6.1 plus

- CHANGELOG.md
- ios/RNDeviceInfo/RNDeviceInfo.m
Added iPad 7th gen deviceId to model mapping for getModel() feature
| Android |    NA     |
| Windows |    NA     |
* [na] I have tested this on a device/simulator for each compatible OS
* [na] I added the documentation in `README.md`
* [na] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [na] I updated the dummy web/test polyfill (`default/index.js`)
* [na] I added a sample use of the API (`example/App.js`)
> Added ios device

- src/internal/devicesWithNotch.ts
Added missing Motorola One Vision to devices with notch list.
PS: I followed the Capitalize style for brand and model, but when tested on a real device it's lowercase.
This don't breaks thing because the method compare transforming to lowercase
https://github.com/react-native-community/react-native-device-info/blob/cd3643326033fe0c9920b763905611565bc3a474/src/index.ts#L767-L768
| Windows |    ✅    |
> Add Motorola One Vision to devices with notch list

- README.md
I only fixed an information on README.
> [FIX] Update some informations on README

- README.md
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- example/App.js
- ios/RNDeviceInfo/RNDeviceInfo.h
- ios/RNDeviceInfo/RNDeviceInfo.m
- src/index.js.flow
- src/index.ts
- src/internal/privateTypes.ts
Fixed issue #643 
Added `isHeadphonesConnected()` that allows checking wired headset or Bluetooth headphones connected status
> Added headphones support

- README.md
- example/App.js
- src/index.js.flow
- src/index.ts
- src/internal/types.ts
Added `useFirstInstallTime()` that simply wraps async function, `getFirstInstallTime()`, into a hook.
_**Note**: The src can be used as a template for wrapping the rest of the async functions into hooks where applicable._
> Adding useFirstInstallTime()

- README.md
- example/App.js
- src/index.js.flow
- src/index.ts
- src/internal/async-hook-wrappers.ts
- Added `useDeviceName()` that wraps `getDeviceName()`
- Added internal utility function, `useOnMount(...)`,  to simplify the _'hookification'_ (patent pending) of some async functions
> Simplifying hookification and adding use device name

- README.md
- example/App.js
- src/index.js.flow
- src/index.ts
Added `useHasSystemFeature(feature: string)` that hookifies `hasSystemFeature(feature: string)`
> Adding useHasSystemFeature

- ios/RNDeviceInfo/RNDeviceInfo.m
Fixed issue #873
| Android |    n/a     |
| Windows |    n/a     |
* [n/a] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [n/a] I added a sample use of the API (`example/App.js`)
> Ensure preferredContentSizeCategory is only called from the main thread

- src/index.js.flow
> changed the type for hasNotch() to boolean

- README.md
> Fix: Typo of README

- CHANGELOG.md
- src/internal/devicesWithNotch.ts
Added Xiaomi Mi 9 to devices with notch
> Fix: add Xiaomi Mi 9 to devices with notch

- ios/RNDeviceInfo/RNDeviceInfo.m
> Fix getDeviceToken crash on IOS simulator

- package.json
Fixes #936 
replace yarn in scripts with `bob` and `npm run`. so it is not required to install this library with npm
> Fix: #936 replace yarn in scripts with bob and npm run. so it is not required to install this library with npm

- android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java
> Gracefully handle missing install referrer permission, Fixes #955

- src/internal/devicesWithNotch.ts
Added missing Motorola One Vision to devices with notch list.
> Add Redmi Note 8 to devices with notch list

- android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java
Fixes #975 
* [ X] I have tested this on a device/simulator for each compatible OS
* [ X] I added the documentation in `README.md`
* [ X] I mentioned this change in `CHANGELOG.md`
* [ X] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ X] I added a sample use of the API (`example/App.js`)
> added more wide exception handling

- CHANGELOG.md
- src/index.ts
Fixes memoization of boolean values. Previously memoization worked only when value was `true`.
> fix: memoization of boolean values.

- example/ios/Podfile.lock
- example/ios/example.xcodeproj/project.pbxproj
- example/yarn.lock
- package.json
- src/web/index.js
- yarn.lock
Update all of the dependencies etc
> chore: yarn update / web lint update

- src/internal/devicesWithNotch.ts
Fixes #1036 
Added Blackview A30 to the list of devices with Notch
> fix(hasNotch): add device Blackview A30

- README.md
Fixes wrong link of `getInstanceId()` in readme
> fix: fix getInstanceId() wrong link

- windows/RNDeviceInfo/RNDeviceInfo.csproj
> [Windows] Fix vNext issue where module did not work on C++ app

- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
> Fixed incorrect value in getFreeDiskStorageSync

- src/index.ts
- src/internal/privateTypes.ts
- src/internal/supported-platform-info.ts
re #1085
- Added a helper/convenience function, `getSupportedPlatformInfoFunctions(...)` that gets rid of some of the repetitive logic around supported platforms and memoization
- Added helper functions, `getSupportedPlatformInfoSync` and `getSupportedPlatformInfoAsync` , that can be used to explicitly get info sync or async if one desires to do so
- unable to verify on Windows, but did verify for iOS and Android
Below are screen shots of iOS and Android and the updated `getDeviceName*` functions (no difference)
> Adding getSupportedPlatformInfoFunctions

- src/index.ts
re #1085
Rewrites the following functions to use `getSupportedPlatformInfoFunctions`
- `getAvailableLocationProviders*`
- `isLocationEnabled*`
- `isAirplaneMode*`
- `isBatteryCharging*`
- `getBatteryLevel*`
- `getTotalMemory*`
- `getPhoneNumber*`
- Tested on iOS and Android, but alas, I'm unable to do on Windows
- also, does the example project currently support web?
> using getSupportedPlatformInfoFunctions

- src/index.ts
re #1085
rewrites the following components to use `getSupportedPlatformInfoFunctions`:
- `getTotalDiskCapacity*`
- `getLastUpdateTime*`
- `isEmulator*`
- `getCodename*`
- `getPreviewSdkInt*`
- `getType*`
- tested on iOS and Android, but unable to test on Windows
@mikehardy,
Thoughts on adding the `hacktoberfest` topic to this repo during October? I'd love to just work on this project and not have to work on other projects that I'm not too interested in to get a tree planted this year. (Purely a selfish request, so totally fine with a _"na, I'm good"_)
> more usage of `getSupportedPlatformInfoFunctions`

- ios/RNDeviceInfo/RNDeviceInfo.m
- src/internal/devicesWithNotch.ts
add iPhone 12 device info
| iOS     |    ✅  |
> add iphone 12 info

- src/internal/devicesWithNotch.ts
Added Samsung A21s to the list of devices with Notch
> fix(hasNotch): add Samsung A21s

- README.md
Updated readme for useFirstInstallTime
Docs only
* [NA ] I have tested this on a device/simulator for each compatible OS
* [NA ] I mentioned this change in `CHANGELOG.md`
* [ NA] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ NA] I added a sample use of the API (`example/App.js`)
> docs: update useFirstInstallTime in readme

- __tests__/getters.test.ts
- __tests__/supported-platform-info.test.ts
- jest.setup.ts
re #1108
- updates `getters` test file to be more scalable
- adds testing for memoized string getter functions
- fixes a mock used internally only (found by testing)
- adds testing for `supported-platform-info`
> testing memoized string getters and supported-platform-info

- ios/RNDeviceInfo/DeviceUID.m
Fixes #1119
Could you help me test it?
> 1119: Change keychain access control

- __tests__/getters.test.ts
- jest.setup.ts
- src/index.ts
re #1108
Updates some getters for better testability of memoization:
- `getSystemName`
- `getUserAgent`
- `geUserAgentSync`
Updates Jest setup to use current platform's option before coercing
Adds tests for the following functions:
- `getSystemName`
- `getUserAgent`
- `getUserAgentSync`
- `getgetAvailableLocationProviders*`
- `getPowerState*`
> Adding more tests and refactoring some getters

- src/internal/devicesWithNotch.ts
Fixes Redmi 9 has notch
* [x ] I have tested this on a device/simulator for each compatible OS
> Redmi 9 has notch

- .github/workflows/linting.yml
- .github/workflows/tests_e2e.yml
- __tests__/async-hook-wrappers.test.ts
- __tests__/getters.test.ts
- example/ios/Podfile.lock
- jest.setup.ts
- jest/react-native-device-info-mock.js
- package.json
- src/index.ts
- src/internal/asyncHookWrappers.ts
- src/internal/types.ts
- yarn.lock
Bringing up android / ios CI so that PRs show complete native complication
Should avoid spending unnecessary time in the future as on #1151
> add ios/android CI, update dependencies

- android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java
Fixes:
https://github.com/react-native-device-info/react-native-device-info/issues/1149
Fixes #<issue-number>
> feat: Add ability to run without com.android.installreferrer

- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Added the ability to run without gms libraries. This is a requirement for publication on F-Droid.
> feat: make gms dependency optional

- README.md
Small doc fix for `hasGms` and `hasHms` functions
> hasGms & hasHms doc fix

- CHANGELOG.md
- src/internal/devicesWithNotch.ts
> add new device with notch: Pixel 4a

- ios/RNDeviceInfo/RNDeviceInfo.m
> arm64 iOS simulators support

- .github/workflows/release.yml
- package.json
- adds a new script, `ci:shipit` , that just executes semantic-release
- updates GH Action workflow to use new script
| iOS     |    N/A     |
| Windows |    N/A    |
> ci: adding and using ci:shipit

- ios/RNDeviceInfo/RNDeviceInfo.m
Fixes #1135 by replacing the use of `inet_ntoa` with `inet_ntop`.
| iOS     |     ✅     |
> fix(ios): Remove IPv4-only method use to prevent App Store warnings

- .github/dependabot.yml
removes dependabot config for auto-updates because we don't get much out of it
re #614
| iOS     |   N/A     |
| Android |   N/A     |
| Windows |   N/A     |
> ci(.github): removing dependabot.yml

- README.md
> Add Proguard config for install referrer

- README.md
> docs(README): Update grammar on isCameraPresent

- ios/RNDeviceInfo/RNDeviceInfo.m
Adds iPad Air 4th gen name description.
* [ x] I have tested this on a device/simulator for each compatible OS
* [ n/a] I added the documentation in `README.md`
* [ n/a] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ n/a] I added a sample use of the API (`example/App.js`)
> fix(iOS): Adds iPad Air 4th gen name description.

- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- ios/RNDeviceInfo/RNDeviceInfo.m
> fix: addListener/removeListeners native stubs for react-native 0.65 compatibility

- README.md
Fixes #1300
* [X ] I have tested this on a device/simulator for each compatible OS
> docs(README): add proguard rule note for hasGms android release build issue

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/issue_template.md
- MAINTAINERS.md
- README.md
Replaces various usage of `react-native-community` with `react-native-device-info`
| iOS     |    N/A    |
> docs: s/react-native-community/react-native-device-info/

- README.md
This is a mini PR to help people find the docs about hooks and events.
The README is pretty long and if one does not scroll down below the long API section it is very likely that one never knows about the nice hooks of this lib. This happened to me.
| Windows |    ✅    |
> docs: add link to hooks and events

- extendGetVersionDoc
> docs: extend the getVersion documentation

- src/web/index.js
> fix(web): Illegal invocation from getBattery call

- README.md
> docs: Fix typo in getVersion description.

- jest/react-native-device-info-mock.js
Adding `hasDynamicIsland` to the jest mock to prevent test failure and having to override global mock in your own project.
> chore: add hasDynamicIsland mock

- src/internal/devicesWithNotch.ts
Add Samsung A202F to the list of devices with notch.
> fix(android): add Samsung A202F to notch device list

- windows/code/RNDeviceInfoCPP.h
feat(windows): implementation of EnergySaverStatusChanged to emitt event RNDeviceInfo_powerStateDidChange
add subscription to EnergySaverStatusChanged in Initialize and sent event RNDeviceInfo_powerStateDidChange with latest powerstate details
Fixes #1518 
| OS      | Existing | Implemented |
| ------- | :---------: | :---------: |
| iOS     |    ✅     |    ❌     |
| Android |    ✅     |    ❌     |
| Windows |    ❌     |    ✅     |
> feat(windows): implementation of EnergySaverStatusChanged to emitt event RNDeviceInfo_powerStateDidChange

- README.md
> docs: add android userAgent example to readme

- android/build.gradle
Starting from React Native v0.73 , all libraries will need to be updated with these two one-liners due to Android Gradle Plugin upgrade
[discussions-671](https://github.com/react-native-community/discussions-and-proposals/issues/671)
> feat(android): add support for React Native 0.73

- README.md
- src/index.ts
- windows/code/RNDeviceInfoCPP.h
Added windows implementation of getHost(). Using this user can get full name of windows devices.
Fixes #1549
| OS      | Existing| Implemented |
| ------- | :---------: | :---------: |
| iOS     |    ❌     |    ❌     |
| Android |    ✅     |    ✅     |
| Windows |    ❌     |    ✅     |
* [] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [] I added a sample use of the API (`example/App.js`)
> feat(windows): Implemented gethost() for windows

- ios/RNDeviceInfo/RNDeviceInfo.m
- src/internal/devicesWithDynamicIsland.ts
- src/internal/devicesWithNotch.ts
Add device names for iPhone 15 family, add check for dynamic island
Fixes #1566
> feat: Add device names for iPhone 15 family, add check for dynamic island

- README.md
- android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
- example/App.js
- src/index.ts
- src/internal/privateTypes.ts
Added `getSupportedMediaTypeList()` that allows to find supported Codecs for device
> feat(android): implemented getSupportedMediaTypeList method

- .github/workflows/jest-test.yml
- .github/workflows/linting.yml
- .github/workflows/pr_title.yml
- .github/workflows/release.yml
- .github/workflows/tests_e2e.yml
- .github/workflows/windows-app-test.yml
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/example.xcodeproj/project.pbxproj
Noticed in #1623 that CI was failing due to bitrot, this is the minimal viable set of changes to get CI clean
> chore(ci): fix workflow files action versions / android e2e execution

- android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java
This PR addresses an ANR (Application Not Responding) issue in the RNInstallReferrerClient class by refactoring network operations to run in background threads.
I can confirm that I have used this code in our react-native mobile app, and released it to production.
We haven't had any ANRs as of now.
1. Introduced an ExecutorService to manage background threads.
2. Moved the initialization of InstallReferrerClient and the invocation of startConnection to a background thread.
3. Ensured that the `onInstallReferrerSetupFinished` and `onInstallReferrerServiceDisconnected` callbacks were posted back to the main thread using a Handler. The network call within onInstallReferrerSetupFinished is now executed in a background thread to prevent blocking the main thread.
This was done as per the …
> fix(android): avoid ANR with use of background thread in RNInstallReferrerClient

- android/build.gradle
- android/src/main/java/com/learnium/RNDeviceInfo/resolver/DeviceIdResolver.java
Fixes https://github.com/react-native-device-info/react-native-device-info/issues/1671
> fix: RNDeviceInfo is adding AD_ID permission through play-services-iid
