react-native-device-info/react-native-device-info

RNDeviceInfo.podspec
With use_frameworks! enabled in my PodFile, I get a linker error:
Undefined symbols for architecture x86_64:
"_RCTRegisterModule", referenced from:
+[RNDeviceInfo load] in RNDeviceInfo.o
ld: symbol(s) not found for architecture x86_64
This is fixed by adding React as a dependency in the podspec
=> Add dependency on React pod

RNDeviceInfo/RNDeviceInfo.m, android/src/main/AndroidManifest.xml, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, deviceinfo.js
I needed to get the user defined device name for my project so I made these changes to allow for it.
They have the unfortunate side effect of requiring the Bluetooth permission on Android so I don't think this pull request should necessarily be accepted but its here if someone needs/wants it.
=> Add user defined deviceName field

android/build.gradle
Reference:
https://github.com/square/okio/issues/58
=> Set lint warning for InvalidPackage, instead of error

README.md, RNDeviceInfo/RNDeviceInfo.m, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, deviceinfo.js
I had a need to get the OS's UserAgent string. I didn't see any way to pull it from React Native directly so I figured the library that provides device info would make the most sense.
=> Add UserAgent as an available bit of information

deviceinfo.js
Running into an issue when unit testing RN from the CLI. Since [Node doesn't support it yet](https://kangax.github.io/compat-table/es6) it will break. 
```
var { RNDeviceInfo } = require('react-native').NativeModules;
^
SyntaxError: Unexpected token {
```
=> Avoid destructuring to support Node.js

RNDeviceInfo/RNDeviceInfo.m
Apple uses lowercase `s` for all devices since 5s model
=> Update device names to respect Apple Branding

RNDeviceInfo/RNDeviceInfo.m, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, deviceinfo.js
Provides the ISO country string derived from the application's locale.
@rebeccahughes: wasn't sure if this was the best key name; please advise if you'd prefer something different.
=> Add support for device country

README.md, RNDeviceInfo/RNDeviceInfo.m, deviceinfo.js
Returns full build version on iOS, use with [xcode-git-version.sh](https://gist.github.com/karlvr/c93a98d7000ecb163895) to print complete git info.
(Not sure what it'll do on Android)
=> Add build version

README.md, RNDeviceInfo/RNDeviceInfo.m, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, deviceinfo.js
android is using value from `Build.BRAND`
ios is using fixed value `"Apple"`
=> add getBrand() on both android and ios

RNDeviceInfo.xcodeproj/project.pbxproj, RNDeviceInfo/RNDeviceInfo.h
https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d moves header imports to `<React/*>`. This updates header include path and all imports so build works against react master (soon to be version 0.40.0).
=> Update iOS RN header paths

RNDeviceInfo/RNDeviceInfo.m
Prevent a crash if `CFBundleShortVersionString` is not defined in info.plist
=> Fix missing CFBundleShortVersionString crash

RNDeviceInfo.xcodeproj/project.pbxproj
Hi @rebeccahughes 
Hope all is going well.
This PR adds the DeviceUID.h file to the 'copy files' build phase, making it available to import and use at the Objective-C/Swift level in your app. This makes it possible to reuse the same code used at the react native level,  in the rest of your project, for example in extensions or other native code.
Cheers,
Marcus
=> Add DeviceUID.h to public headers

deviceinfo.d.ts
Reverting #12c93cb that has broken TS support.
based on @aarondail's issue: 
https://github.com/rebeccahughes/react-native-device-info/issues/208
We've bumped into the same problem.
=> fix(Types): TS type definitions didn't use the correct export mechanism

RNDeviceInfo/RNDeviceInfo.m
With the release of the iPhone X it is essential to know the device model to change the behavior of View, even when using an iOS Simulator. So I implemented the function to detect the device model even inside the simulator.
Changes:
- Added device detection even when in an iOS emulator.
- Additionally, added device types for iPhone 8, iPhone 8 Plus and iPhone X.
=> Added device detection even when in an iOS emulator.

RNDeviceInfo/RNDeviceInfo.m
Now supports iPad Pro 10.5-inch, 2nd Generation iPad Pro 12.5-inch, Apple TV 4K, and additional models of iPhone 8, 8s and X.
=> Add support for new iPhone, iPad, and Apple TV models

RNDeviceInfo/RNDeviceInfo.m
Warning: Module RNDeviceInfo requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
=> Fix RN 0.48+ warning about requiresMainQueueSetup

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
[Android][bug] Neither user nor current process has android.persmission.ACCESS_WIFI_STATE
Hello!
After update from 0.11.0 to 0.12.0 it crashes on install
This PR not force people to add wifi permission and leave 2 new methods "getIP" and "getMac" only to folks who need it.
=> Fix "Neither user nor current process has android.persmission.ACCESS_WIFI_STATE"

RNDeviceInfo/RNDeviceInfo.m
=> Fixing `@synthesize isEmulator` duplicate

windows/RNDeviceInfo/RNDeviceInfoModule.cs
This dependency is not required. It also stops the project from being used.
=> Removed an unused dependency

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixes #272 
Stack trace for crash:
```
Java exception in 'NativeModules' android.util.AndroidRuntimeException: 
android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview, 
stack: 
android.webkit.WebViewFactory.getFactoryClass@174 
android.webkit.WebViewFactory.getProvider@109 
android.webkit.WebSettings.getDefaultUserAgent@1229
```
=> Add fallback when webview is not installed

RNDeviceInfo/RNDeviceInfo.m
The name of the native module export on IOS sometimes differ from the one used in the JS code, specifying the name of the module fix the problem
Fix #236
=> Fix export module name

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
`error: exception NameNotFoundException is never thrown in body of corresponding try statement`
This error happen during compile due to WebSettings.getDefaultUserAgent throw `RunTimeException` instead of `PackageManager.NameNotFoundException`
This fix would catch the right exception
=> Catch right exception on RNDeviceModule

RNDeviceInfo.podspec, RNDeviceInfo/RNDeviceInfo.m
Updated tvOS support, because this system doesn't include CoreTelephony framework.
=> updated tvOS support

README.md
`yarn addreact-native-device-info` ➡️  `yarn add react-native-device-info`
=> docs: add missing space after yarn add

README.md
Fixed issue #314 
Changed the code example of `getUniqueId()` to `getUniqueID()`
=> docs: fix typo in getUniqueID() method example

CHANGELOG.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixed issue #318 by using Android methods available since API Level 1
=> fix: make getTotalDiskCapacity() and getFreeDiskStorage() available < SDK18

CHANGELOG.md, README.md, android/build.gradle
Added a new Gradle build config that pulls the root-project ext variable  `googlePlayServicesVersion` if it exists and sets the module's play-services-gcm version. It defaults to `+` if it doesn't exist mimicking the current functionality. 
Gradle Build Configuration
* ✅ I have tested this on a device/simulator for each compatible OS
* ✅ I added the documentation in `README.md`.
* ✅ I mentioned this change in `CHANGELOG.md`.
=> feat: Google play services versioning

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Changed the nature of IsTablet for Android, since newer devices with higher dp and screensizes returns as tablet, needs further testing.
=> fix: enhance isTablet() on Android

README.md, android/src/main/AndroidManifest.xml, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceReceiver.java, deviceinfo.js, web/index.js
Added `getInstallReferrer()` that returns the install referrer attribution when your android app gets installed (com.android.vending.INSTALL_REFERRER). You can use https://play.google.com/store/apps/details?id=com.myapp&referrer=<your custom referrer string here>
| iOS     |   ❌     |
| Windows |   ❌     |
=> feat: add getInstallReferrer() for Android

RNDeviceInfo.podspec
=> fix: remove deprecated React pod dependency

RNDeviceInfo/RNDeviceInfo.m
=> fix(getBatteryLevel): change method to respect tvos targets

README.md
This commit will clarify in the README that both "iOS" and "iPhone OS" are possible return values from calling getSystemName when running on an iOS device. "iOS" being reported on most iOS 10+ devices and "iPhone OS" reported on iOS 9 and less and some iOS 10 devices.
Fixed issue #410
=> docs: clarify iOS return values of getSystemName

android/build.gradle, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixed issue #459
* When I created react-native app from `create-react-native-app`, android build is fail.
* `Build.VERSION_CODES.N` and `getLocales()` is availabed in from Android SDK 24. Thus, `compileSdkVersion` should be at least 24.
=> Fix android build error

.gitignore, CHANGELOG.md
The currently published nom package (v0.22.3) is 28.2 MB, unpacked, because it includes a copy of the generated Android build files. By ignoring the folder `android/build` in `.gitignore`, npm will also ignore that folder, and the build artifacts will no longer wind up on in the npm package.
Before: 28.2 MB
After: 187.9 kB
=> chore: Ignore the Android build/ folder

deviceinfo.d.ts
In #466 the export of the main module was changed to use default export.
Change the typescript declaration to use default export, too.
=> fix(deviceinfo.d.ts): fix typescript declaration export

android/build.gradle
With the latest react-native version RN >= 0.57 the android build tools were updated and now using compile in the build.gradle file generates the following error:
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Please note that this also happens to people that manually updated their android build tools from the previous defaults
This is a change in the android/build.gradle file that only affects android builds, it doesn't add or remove functionality.
Items 2 and 3 in the checklist are not …
=> build: Update build.gradle to remove compile warning

deviceinfo.js
To have a more robust code we should compare brand and model after using lowercase
Please tell me what you think of it
* [ x ] I have tested this on a device/simulator for each compatible OS
=> compare hasNotch devices with lowercase

README.md, android/src/main/java/com/learnium/RNDeviceInfo/DeviceType.java, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, deviceinfo.d.ts, deviceinfo.js, deviceinfo.js.flow, ios/RNDeviceInfo/RNDeviceInfo.m, web/index.js
- getDeviceType will return: Handset, Tablet, Tv, or Unknown
- Supported on iOS and Android.  Always set to Unknown on web. Unsupported on windows
- On iOS/Android, modified isTablet logic to just check if deviceType == Tablet
On iOS, device type detection is done via user interface idiom detection for the device and is thus exact.
On Android, TV platform detection checks for both Android TVs (via UI manager mode) and FireTVs (via system feature check). For non TV devices we attempt to calculate the physical screen size (diagonal) and set some sane cutoffs for when a device is a Handset (3" -> 6.9") or a Tablet (7" -> 18"). If detection fails the deviceType is set to Unknown.
| Windows |    ❌ …
=> feat(android/ios): Adding getDeviceType function and changing behavior of isTablet

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, deviceinfo.d.ts
Fixed issue #331 
There are other PRs floating around for this one but they are all messy or abandoned or both.
This is a very focused change that changes the use of the existing native API calls (which are deprecated but also work back to the react-native supported API16) so that they are computed with protection against integer overflow per this comment from @knot123: https://github.com/rebeccahughes/react-native-device-info/issues/331#issuecomment-428848892
There are valid reasons why you might want to use different native API calls to total up space in Android but you could also argue those are all behavior changes for this module API, so this just fixes the overflow and leaves it at that
=> Use BigInteger to avoid overflow (Fixes #331)

deviceinfo.d.ts
A simple typing fix. I'm not the best at Typescript definitions, but this small change results in Typescript transpiling code that looks like the readme with no issues, and I have verified the callback is being called on a real device
Fixes #486
=> Alter isPinOrFingerprintSet typing so it is a function

README.md, ios/RNDeviceInfo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, ios/RNDeviceInfo/RNDeviceInfo.m
Fixed issue #396
Enabled battery monitoring mode to get actual battery data
=> Enabled battery monitoring mode to get actual battery data

deviceinfo.js
Fixed issue #581 
`DeviceInfo.getModel()` returns `'POCOPHONE F1'`, however currently this is getting matched against `'POCO F1'`, which evaluates to `false`. This fixes it.
=> hasNotch should return true for Pocophone F1

CHANGELOG.md, android/build.gradle
Took the advice from a comment on the linked issue: https://github.com/react-native-community/react-native-device-info/issues/325#issuecomment-448498293
Should fix #325
=> Ignore missing permissions in lint, specify minor support library versions

RNDeviceInfo.podspec
For example version is now hardcoded antique 0.21.5. So why not get needed details from package.json and those are always up-to-date.
Fixed podspec to be more dynamically.
=> Getting podspec details from package information

CHANGELOG.md, README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, deviceinfo.d.ts, deviceinfo.js, deviceinfo.js.flow, example/App.js, ios/RNDeviceInfo/RNDeviceInfo.m
Fixed issue #578 
Added `supportedABIs()` which returns a list of supported device cpu types
=> feat: Added DeviceInfo.supportedABIs()

README.md
Fixed issue #562
Added troubleshooting info for CoreTelephony error log - *[NetworkInfo] Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099  “The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.”*
=> docs: Added troubleshooting info for CoreTelephony error log

CHANGELOG.md, deviceinfo.js
Added a device (ONEPLUS A6010) to `devicesWithNotch` since it has a notch.
=> ONEPLUS A6010 has a notch

CHANGELOG.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Uses this.reactContext instead of getCurrentActivity to check permissions for phoneNumber getter
getCurrentActivity would return null very often, and would render getPhoneNumber function useless.
Using this.reactContext to check the permissions is more reliable.
=> Uses this.reactContext instead of getCurrentActivity to check permissions for phoneNumber getter

CHANGELOG.md, README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Ask relevant permissions according to Android os version. Issue: #268 
Relevant links for Android source code, each page shows what permissions getLine1Number method requires.
[Lollipop - TelephoneManager source code](https://android.googlesource.com/platform/frameworks/base.git/+/lollipop-release/telephony/java/android/telephony/TelephonyManager.java)
[Marshmallow - TelephoneManager source code](https://android.googlesource.com/platform/frameworks/base.git/+/marshmallow-release/telephony/java/android/telephony/TelephonyManager.java)
[Nougat - TelephoneManager source code](https://android.googlesource.com/platform/frameworks/base.git/+/nougat-release/telephony/java/android/telephony/TelephonyManager.java)
[Lollipop - TelephoneManager source …
=> Ask phoneNumber permissions according to Android os version

CHANGELOG.md, windows/RNDeviceInfo/RNDeviceInfo.csproj
@mikehardy, 
This is the required change that is necessary for windows to resolve the reference path in different environments (outside of visual studio which automatically resolves references).
=> dynamic pathing for windows, actual diff to #357

CHANGELOG.md, README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, default/index.js, deviceinfo.d.ts, deviceinfo.js, deviceinfo.js.flow, example/App.js, ios/RNDeviceInfo/RNDeviceInfo.m
This PR exposes the functions to return the preferred languages set up by the user in the Android and iOS devices.
As a user, you can customize what are your preferred languages. Right now, `react-native-device-info` just return the first value from this list, but there are scenarios where we need to have the whole preferred languages in order to see if they fit with the supported language that the `react-native-app` support.
Added `getPreferredLocales()` that returns the list of preferred languages set up in the Android or iOS device.
* [✅] I have tested this on a device/simulator for each compatible OS
* [✅] I added the documentation in `README.md`
* [ ✅] I mentioned …
=> feat: Add preferred Languages function

CHANGELOG.md, README.md, default/index.js, deviceinfo.d.ts, deviceinfo.js, deviceinfo.js.flow, example/App.js, example/ios/example/AppDelegate.m, ios/RNDeviceInfo/RNDeviceInfo.h, ios/RNDeviceInfo/RNDeviceInfo.m, refresh-example.sh
Added `getPowerState()` that allows for fetching more detailed information about the power on the device. In addition to returning the battery level it includes information about the battery state (full, charging, etc.) and whether the system is operating in low power mode.
Additionally, this adds a few events that can be subscribed to in order to be notified when the battery level changes, state changes (for example, if the device is unplugged), or if the battery drops below 20%.
These additional capabilities are very helpful in our case as we want to trigger certain things within our app when an app intended for kiosk use is unplugged and starts depleting battery. It's also useful to know if the battery is low or the user has switched on low power mode so that we can defer certain …
=> feat: add battery monitoring and detailed power state getter

CHANGELOG.md, README.md, ios/RNDeviceInfo/RNDeviceInfo.m
I've added the 3rd generation Ipad pro to the list with available devices. This fixes a problem where it just returns "iPad" for these devices.
I've specifically added 3th generation to the name of the device. This way you can actually tell the difference between the multiple versions of the iPad Pro. This is a must have because it's the only way to tell the difference between the iPad pro with physical home button (generation 1 and 2) and the iPad pro without physical home button (generation 3). I kept the name of generation 2 the same for now but I can rename it for consistency.
=> Add the 3th generation iPad pro to the device name list

RNDeviceInfo.podspec, package-lock.json
There is some discussion amongst the rest of the react-native-community about standardizing the Podspec - https://github.com/react-native-community/meta/issues/15#issuecomment-478681151
Ours was close to the one held up for discussion but there were two obvious errors and a warning that we can fix now
- we were pulling master in the podspec but we should pull the version from json
- the ios target was 8 but react-native only supports down to 9
- there was no platform version specified (should be 9)
=> Podfile update

CHANGELOG.md, README.md, ios/RNDeviceInfo/RNDeviceInfo.h, ios/RNDeviceInfo/RNDeviceInfo.m
Fixes #347.
Calling `[UIApplication sharedApplication]` [is unsafe in an app extension][0]. This is hidden by `RCTSharedApplication` which lets app extensions include this library through CocoaPods [without compilation errors][1].
[0]: https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6
[1]: https://github.com/CocoaPods/CocoaPods/pull/3048
>I don’t think this is necessary for this PR.
=> Use RCTSharedApplication instead of [UIApplication sharedApplication]

.flowconfig, package-lock.json, package.json
This is related to #614 - it doesn't implement CI but in looking at #613 I realized we could at least run a flow check from the command line. We also provide typescript definitions, so I added the ability to check that as well
It is not integrated with anything automated at the moment, that would be the real CI solution traced as #614
=> chore: add ability to test flow and typescript definitions from command line

CHANGELOG.md, deviceinfo.js
Fixed issue #621 
| Windows |    ✅*     |
* Due to lack of devices/OS I was not able to test the Windows part.
Didn't do the above steps as I feel those aren't needed for this PR.
=> Fixed #621 Feat: Throw an error if the native module is null with steps to help fix the issue

CHANGELOG.md, README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, default/index.js, deviceinfo.d.ts, deviceinfo.js, deviceinfo.js.flow, example/App.js, ios/RNDeviceInfo/RNDeviceInfo.m, windows/RNDeviceInfo/RNDeviceInfoModule.cs
Added `getBuildId()` that allows to gets build number of the operating system.
> **Note**: This method helps users' want's to [integrate with **Google Ads**](https://developers.google.com/app-conversion-tracking/api/request-response-specs) and this parameter is required to track their campaigns.
| iOS          |     ✅     |
| Android   |     ✅     |
| Windows |     ✅     |
=> Add build number of the operating system.

CHANGELOG.md, ios/RNDeviceInfo.xcodeproj/project.pbxproj, ios/RNDeviceInfo/RNDeviceInfo.m
Fixed a build issue on tvOS in xcode 10.2. tvOS Header Search Paths were missing and couldn't find the `<React/RCTUtils.h>`. Also, `batteryState` is not available for tvOS and xcode failed to build, so I updated the if statement.
=> fix: building issue on tvOS / header on iOS

CHANGELOG.md, ios/RNDeviceInfo/RNDeviceInfo.m
Fix iOS build issues - there were two incompatible pointer types, and we were not following convention in a macro usage
This makes it so when you include this module it builds cleanly
This should be backwards compatible and just a patch version
=> chore: fix pointer types and macro usage based on XCode warnings

RNDeviceInfo.podspec
When missing the v for the tag name, directly referencing the podspec file can result in a "tag not found" error when doing a pod install.
Fixed issue #659 
| Windows |   ❌     |
=> fix: added v to tag name in podspec

deviceinfo.js, package-lock.json, package.json
react-native-community has some nascent standards, and [the use of lint is one of them](https://github.com/react-native-community/.github/issues/9).
I've patterned this off the [work in react-native-maps](https://github.com/react-native-community/react-native-maps/pull/2862), netinfo etc - [guidance here](https://github.com/facebook/react-native/tree/master/packages/eslint-config-react-native-community)
Basically, this installs the requisite lint package and since we had no lint standard before, I just extended the community standard in in package.json
Our prettierrc was already similar, so there were very only 4 errors to fix
To ensure we don't skew over time, I installed lint-staged and husky, and configured the module to run eslint in fix mode as a commit hook
=> chore: integrate react-native-community/eslint standards

CHANGELOG.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
This PR switches two `StatFs` method calls in `getFreeDiskStorage()` to use their newer, `long`, variants when available (instead of older, deprecated versions). 
Fixed issue #N/A
| iOS     |    ✅ (n/a)     |
| Windows |    ✅ (n/a)     |
=> fix: use non-deprecated APIs where available in `getFreeDiskStorage()`

CHANGELOG.md, ios/RNDeviceInfo/RNDeviceInfo.m
=> fix(tvOS): Adding tvOS to isBatteryMonitoringEnabled ignore check

deviceinfo.d.ts
These are just type fixes from a couple recent PRs
I'm still getting better at Typescript so I didn't realize these would be problematic as submitted until I attempted to use them in a project and there were complaints about the return values.
Since they have known types from the native code, I made them specific.
I don't know enough about flow to do those but would love if someone did, or maybe we can leave them generic.
Also, I am not sure about the breaking nature of this or not - but I think if we are going from less-specific to more-specific it shouldn't break anyone?
=> types: make the typescript location / power returns specific

CHANGELOG.md, example/ios/example/AppDelegate.m, example/package.json, example/yarn.lock, ios/RNDeviceInfo/RNDeviceInfo.m, refresh-example.sh
Adding conditions to only check if location services is enabled, because tvOS doesn't support `significantLocationChangeMonitoringAvailable`, `headingAvailable` and `isRangingAvailable`.
| tvOS     |    ✅     |
=> fix: adding conditions for tvOS location providers

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceInfo.java, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
RNDeviceModule.getConstants() can take a lot of time (~300ms on a Galaxy S7), so try to run it as soon as possible in the background so that by the time it gets called, the constants have already been calculated and we can just return the map.
=> perf(Android): getConstants() in thread to parallelize load, speed up for most

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceReceiver.java
action is Nullable, so we call equals from action is not safe
```
java.lang.RuntimeException · Unable to start receiver com.learnium.RNDeviceInfo.RNDeviceReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
```
=> fix(Android): Avoid NullpointerException on install referer listener

README.md
Under the iOS "Manual Linking" section, there is no file with the extension `.xcodeproj` in the location specified in the README. I have updated this section to specify the correct location of this file.
=> Readme: Clarify location of RNDeviceInfo.xcodeproj

android/build.gradle
With the latest firebase/gcm release (https://developers.google.com/android/guides/releases), the latest version (`+`) now brings in androidx dependencies. react-native won't be ready for androidx until 0.60 so constraint the gcm version to 16.1.0 (the latest pre-androidx version)
=> Constraint gcm version to 16.1.0

README.md
This PR adds a notice regarding the changes in: https://github.com/react-native-community/react-native-device-info/pull/680
The main reason I left it under the Installation header is because I am afraid people might miss it when using automatic linking.
=> docs(README): Clarify the new changes regarding loading constants async

README.md
Fixed issue #691 
Added a few more contents to the Podfile to result in a successful build.
Adding `pod 'React', :path => '../node_modules/react-native'`
prevents CocoaPods from installing a "React" Pod in the `ios/Pods` directory.
Not adding this line results in multiple versions of "React" being installed in the same project (one in `/node_modules` and the other in `ios/Pods`) which probably results in a conflict.
=> docs: Update Podfile contents under Linking -> iOS (via CocoaPods)

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fix: crash on android api level less than 23
- android.os.Build.VERSION. BASE_OS
- android.os.Build.VERSION. PREVIEW_SDK_INT
- android.os.Build.VERSION. SECURITY_PATCH
**Added in API level 23**
=> Fix: crash on android api level less than 23

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
PREVIEW_SDK_INT was introduced in API level 23 so we should check for Marshmallow not for Lollipop
=> Fix crash for API lower than 23

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixed issue #729 
As described in the Issue #729, the logic used to determine if the `DeviceType` is a Tablet or Handset is now based on the **` smallestScreenWidthDp`**; With fallback on the previous *physical size* based logic in cases when the `smallestScreenWidthDp` is not defined.
=> Fix: isTablet() on Android uses smallest-width-dp when available

README.md
This PR fixes a small typo where the ")" is missing in the API table.
N/A
N/A
=> Fix missing ")" in README.md

CHANGELOG.md, README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceInfo.java
Makes loading module async as default with option to disable this and run sync instead per discussion https://github.com/react-native-community/react-native-device-info/pull/680#issuecomment-515994928
=> Make async loading default

README.md
I stumbled over this when implementing a share extension, which has a different bundle identifier than my main app.
Since I used `getUniqueID()` to construct a User-Agent that needed to be stable for Authentication purposes, this broke auth for me.
=> Mention that `getUniqueID()` can be different in app extensions

README.md, deviceinfo.js, example/App.js
=> Export react-native-device-info to be compatible with destructured ES6 imports

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Add `@ReactModule` annotation and `NAME` constant. This will eventually be used by TurboModules annotation processor.
N/A
=> Add `@ReactModule` annotation and `NAME` constant

CHANGELOG.md, README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixed issue #214
Parse the return integer from PackageManager in to a string, also returns "0" by default instead of 0. 
=> Fix android build number type inconsistency

ios/RNDeviceInfo/RNDeviceInfo.m
The latest version doesn't compile for the tvOS target because if the WebKit imports and usage. This PR adds some additional compiler flags so that it works again for tvOS.
| tvOS/iOS |    ✅   |
* [ x ] I have tested this on a device/simulator for each compatible OS
=> Added tvOS Compiler Flags

README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, deviceinfo.js
Added support for the following events on Android
- RNDeviceInfo_batteryLevelDidChange
- RNDeviceInfo_batteryLevelIsLow
- RNDeviceInfo_powerStateDidChange
=> feat(events): Add support to Android

deviceinfo.js
Fix crash in getModel on iOS. Fixes: #780
Add a few extra devices from:
https://www.theiphonewiki.com/wiki/Models
Fixed issue #780
* [n/a] I updated the dummy web/test polyfill (`default/index.js`)
* [n/a] I added a sample use of the API (`example/App.js`)
=> Fix crash in getModel on iOS. Fixes: #780

CHANGELOG.md, README.md, android/src/main/java/com/learnium/RNDeviceInfo/DeviceType.java, ios/RNDeviceInfo/RNDeviceInfo.m
For consistency, change the casing of `Unknown` to `unknown` like the rest of the library.
If we're happy with this, then we can add it to 4.0.x as a breaking change.
=> refactor: change `Unknown` to `unknown` for consistency

CHANGELOG.md, README.md, android/build.gradle, example/android/build.gradle, example/yarn.lock, refresh-example-rn59.sh, refresh-example.sh
#802 showed that the initial attempt at a backwards-compatible dependency on the specific iid library prompted by #746 vs the full play services library had an error in the pre-AndroidX versioning (and will fail in the future for AndroidX)
This adds a new gradle variable googlePlayServicesIidVersion which targets the specific dependency version, and we will only fall back to the existing googlePlayServicesVersion if the IidVersion is not available. So this should fix the issue and still be compatible with the installed base.
While I was in the area I altered our build.gradle style to conform with current react-native-community best practices from https://github.com/react-native-community/discussions-and-proposals/issues/151#issuecomment-532787908 and I committed a new version of …
=> fix: android use googlePlayServicesIidVersion if available

README.md
Fixed issue #843 
Though return type of hasNotch in API table was right, example code was still Promise-based code.
=> Fix wrong example code of hasNotch() in docs

README.md
Fixed issue in README where it is said that `getDeviceId()` returns a `Promise<string>` when it actually returns a `string`.
=> Fix README saying a promise is returned when it's actually a string.

ios/RNDeviceInfo/RNDeviceInfo.m
Fixed issue #846 
---
`getAppName` will return `CFBundleName` for those cases where `CFBundleDisplayName` is null
=> fix(ios): app display name being null

README.md, android/build.gradle, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, example/android/build.gradle, refresh-example-rn59.sh, refresh-example.sh
iid library: com.google.android.gms:play-services-iid has been deprecated as per: https://developers.google.com/android/reference/com/google/android/gms/iid/package-summary
It has been replaced with firebase
* [X ] I have tested this on a device/simulator for each compatible OS
=> Using latest iid library from firebase

.github/workflows/pr.yml
GitHub actions is still in "Beta", and so things are changing.
Looks like they changed the behavior of &&'s within a script. -- but they have a better way to specify the working directory, which is what I was using this for anyway.
=> Fix github actions definition

android/build.gradle
Removing extra parenthesis that makes Android Studio fail to load project
=> Android build fails due to extra parenthesis

README.md, android/build.gradle, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, android/src/main/java/com/learnium/RNDeviceInfo/resolver/DeviceIdResolver.java, android/src/main/java/com/learnium/RNDeviceInfo/resolver/DeviceTypeResolver.java, android/src/test/java/com/learnium/RNDeviceInfo/resolver/DeviceIdResolverTest.java
Fixed issues caused when not finding either firebase or GMS Id providers. Extracted to a single-purpose class and added Unit tests.
=> Check classes exist

README.md, example/App.js, src/index.js.flow, src/index.ts
Related issue #776 
https://github.com/react-native-community/react-native-device-info/issues/776#issuecomment-545780483
Added `useIsEmulator()` that allows to get whether the application is running in an emulator.
=> add useIsEmulator hook

package.json, src/index.js.flow
The flow syntax was invalid so type checking was failing:
```
Error ------------------------------------------- node_modules/react-native-device-info/lib/commonjs/index.js.flow:18:32
Unexpected token {
18| export type AsyncHookResult<T> {
^
Error --------------------------------------------- node_modules/react-native-device-info/lib/module/index.js.flow:18:32
Unexpected token {
18| export type AsyncHookResult<T> {
^
Error ---------------------------------------------------- node_modules/react-native-device-info/src/index.js.flow:18:32
Unexpected token {
18| export type AsyncHookResult<T> {
^
```
=> Fix flow syntax

src/index.ts, src/internal/nativeInterface.ts
Hi 👋.
I understand using `const OS = Platform.OS` is tempting, but metro replace its usage with the raw value to optimize minification (like `NODE_ENV`)
```ts
const OS = Platform.OS;
export function getUniqueId() {
if (!uniqueId) {
if (OS === 'android' || OS === 'ios' || OS === 'windows') {
uniqueId = RNDeviceInfo.uniqueId;
} else {
uniqueId = 'unknown';
}
}
return uniqueId;
}
// ⬇ Metro
const OS = 'android';
export function getUniqueId() {
if (!uniqueId) {
if (OS === 'android' || OS === 'ios' || OS === 'windows') {
uniqueId = RNDeviceInfo.uniqueId;
} else {
uniqueId = 'unknown';
}
}
return uniqueId;
}
// ⬇ Uglify
export function getUniqueId(){return uniqueId||(uniqueId="android"===OS||"ios"===OS||"windows"===OS?RNDeviceInfo.uniqueId:"unknown"),uniqueId};
```
```ts
export function …
```
=> Inline Platform.OS usages

CHANGELOG.md, README.md, example/App.js, ios/RNDeviceInfo/RNDeviceInfo.m, src/index.ts, src/internal/privateTypes.ts
Implements `getDeviceToken` using [DeviceCheck API](https://developer.apple.com/documentation/devicecheck)
(Closes #658 )
| iOS     |      ✅     |
=> feat(getDeviceToken) add getDeviceToken to get token using DeviceCheck API (ios only)

README.md
Just a simple documentation fix - currently upgrade links in TOC do not scroll view to desired part of readme. This PR fixes that issue.
n/a
n/a
=> Fix upgrade links in README.md TOC

ios/RNDeviceInfo/RNDeviceInfo.m
When building on iOS and forcing pods to use a given deployment target, a warning is thrown as the compiler does not properly check the @available tag if it's joined with another condition.
`@available does not guard availability here; use if (@available) instead`
This PR moves the @available check to its own conditional and then runs the rest of the method as normal. 
Fixed issue #937 
| iOS     |    ✅  |
=> fix: @available does not guard availability here

package.json, yarn.lock
Just a couple of minor `devDependency` updates and alignments:
- `react-native@0.61.5` uses `react@16.9.0`
- Updated `@types/react-native` to 0.61.2 (the latest released version)
`@types/react-native` _already_ has dependency on a matching version of `@types/react`. Removing the explicit declaration prevents potential build errors when versions mismatch.
Tested by successfully running `yarn analyze` before and after the updates.
=> Align and update react-native dependency

CHANGELOG.md, README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, example/App.js, src/index.js.flow, src/index.ts, src/internal/privateTypes.ts
Signed-off-by: Josh Kelly <josh@codecog.dev>
Adds request from Issue #912
`getInstallerPackageName()` provides the ability to fetch the location where an apk was installed from. Return values have been added to the docs.
| OS            | Implemented |
| --------- | :---------: |
| iOS           |    ❌     |
| Android   |    ✅     |
=> feat: add getInstallerPackageName for android

android/build.gradle, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java
Use new `InstallReferrerClient` before to be deprecated by Google Play Store.
Fixed issue <https://github.com/react-native-community/react-native-device-info/issues/909>
Documentation:
- https://developer.android.com/google/play/installreferrer/library.html#java
- https://mvnrepository.com/artifact/com.android.installreferrer/installreferrer
| iOS     |    ❌  |
| Android |     ✅   |
| Windows |    ❌   |
=> install_referrer api over soon to be deprecated

CHANGELOG.md, ios/RNDeviceInfo/RNDeviceInfo.m
device-info is working great for mac catalyst target, except for `getCarrier`.
I just added a macro check to fix this.
Hmm. This is a pretty subtle change and I don't know if I need to modify CHANGELOG and README, etc.
=> fix: add mac catalyst compatibility to getCarrier

CHANGELOG.md, ios/RNDeviceInfo/RNDeviceInfo.m
This appears to have been a simple typo in the iOS implementation of `getModel`. It was checking if `deviceName` was `nil`, and it if _was_, then it was continuing to parse `deviceName`. This was clearly not the intent.
This is such a small fix that I wasn't sure it was worth creating an issue for or adding to `CHANGELOG.md`, but happy to do so if others disagree.
(this fix doesn't affect Android/Windows...)
=> Fix issue where getModel on iOS would never return the generic names, only "unknown" if the real device name wasn't found.

README.md
Improve Docs. 
e.g. `DeviceInfo.getModel()` is not an async API and therefore returns the actual value rathe than a Promise.
=> Improve docs API text

ios/RNDeviceInfo/RNDeviceInfo.m
=> Add AVAudioSessionPortBluetoothHFP to AVAudioSession check

src/web/index.js
Fix issue: TypeError: https://github.com/react-native-community/react-native-device-info/issues/950
```
Quoting: https://github.com/webpack/webpack/issues/4039
You can mix require and export. You can't mix import and module.exports.
```
I simply replaced the module.exports syntax with 'export const' and it does fix the error.
=> Fix: TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

package.json, yarn.lock
Small update to the `devDependencies` in `package.json`:
Use fixed versions of `react` and `react-native`. Prevents unintentional misalignment, and no longer prints the following warning when installing dependenices:
warning " > react-native@0.62.2" has incorrect peer dependency "react@16.11.0".
Also contains a patch update of `@types/react-native` from `0.62.10` to `0.62.12`.
=> Use fixed versions for react and react-native

.github/workflows/pr.yml
As @mikehardy mentioned in #1027 the Windows PR check script was "almost" working. In fact it was a pretty good template to start with, however several things were broken:
The primary reason for the failing build was the `runner.temp` variable which has a **different** value depending on where it's used (in the `working-directory` parameter or in other places). 🤦 This is a known bug on GitHub Actions, see [the community thread here](https://github.community/t/runner-temp-being-emptied-between-jobs/18217). This tripped up the "Nuget restore" and "Build Windows Solution" steps, not finding the generated project where they expected it.
To work around this, we're now simply using `cd` to change into the desired directory before executing a command. Not quite as elegant and idiomatic as using …
=> Fix msbuild windows pr checks

src/index.ts
Previously you knew you would get a PowerState object for instance, but
you could not actually use that type in your project code because it was
not exported
Additionally the LocationProviderInfo type was not even imported, and bob
seemed to handle it okay when generating the lib but it inlined a type requires to do it
which was silly
Fixes #1040
=> fix(types): import LocationProviderInfo type, export result types

ios/RNDeviceInfo/RNDeviceInfo.m
The battery value is 0.00 to 1.00 but the threshold was 0-100, so it
was an expectations mismatch.
Using threshold of 0.20 instead of 20 makes it work
Fixes #1038
I tested this on a real device since you can't simulate battery events on a simulator
=> fix(ios): correctly calculate ios low battery threshold

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, ios/RNDeviceInfo/RNDeviceInfo.m
Android was not listening to power connection events, now it is
Neither platform was triggering on low power mode, now they are
Fixes #1026
=> fix: power connection and power save events were not triggering correctly

ios/RNDeviceInfo/RNDeviceInfo.m
Fixes #774 
We can not use structures and @Property to setter . And must use __block
Otherwise，wkwebview might deallocate before we ask for user Agent
| iOS     |    ✅   |
=> Fix: WKWebview is release

CHANGELOG.md, src/internal/devicesWithNotch.ts
Fixes missing Huawei P30 model name in withNotch list
1. withNotch list has been updated
=> Add Huawei P30 to devicesWithNotch list

android/src/main/AndroidManifest.xml
protects the exported broadcast receiver which listens for app installation intents with the INSTALL_PACKAGES permission to limit it's usage to broadcasters which are able to install packages (usually only the Play Store). This avoids warnings of scanners which check for publicly exported broadcast receivers and restricts that broadcast receiver as much as possible. With the permission set, the users has to explicitly grant an app the install packages permission for it to use the broadcast receiver. (Most users probably won't have any app other than the play store with that permission.) Unfortunately it will still show up as false-positive in MobSF, but with a longer explanation and note about permissions.
Fixes #452 and #554 
This is android only and therefore doesn't require any changes …
=> Protect exported broadcast receiver with install packages permission.

CHANGELOG.md, ios/RNDeviceInfo/RNDeviceInfo.m
I've added the 2nd generation iPhone SE to the list of available devices. This fixes a problem where it just returns "unknown" for this model.
| Android     |    ❌    |
| Windows     |     ❌     |
=> chore: add 2nd generation iPhone SE to device name list

RNDeviceInfo.podspec
Latest Xcode 12 might fail to build when a library does not depend on `React-Core` directly hence this change is necessary for native modules on iOS. This change requires to React Native 0.60.2 or newer and it's not breaking change. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
I have not tested this library with Xcode 12 yet, but most native modules fail so I'm submitting this PR as it's thas not change anything besides changing minimum RN version to 0.60.2.
=> fix: Xcode 12 compatibility

src/index.ts
`getPowerState` returned a Promise that was always types as an empty object.
Correctly it should be the same returnType as `usePowerState` wrapped in a Promise => `Promise<PowerState | {}>`
Fixes #1081
=> fix(types): add returnType to getPowerState

README.md, example/App.js, src/index.js.flow, src/index.ts, src/internal/privateTypes.ts
Added `useManufacturer()` that wraps the async function, `getManufacturer()`, in a hook.
| Windows |    ✅ ❌     |
* I wasn't able to confirm on a Windows box, but was able to do so on iOS and Android. I assume it would work because the core, `getManufacturer()`, is marked as being able to work on Windows.
=> useManufacturer

README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, example/App.js, ios/RNDeviceInfo/RNDeviceInfo.m, src/index.js.flow, src/index.ts, src/internal/asyncHookWrappers.ts, src/internal/privateTypes.ts
#569 
Description
Fixes #1013
- Added hook, `useIsHeadphonesConnected()` , that tells if headphones are connected to the device. 
- Added a new event, `RNDeviceInfo_headphoneConnectionDidChange`,  that is fired by iOS and Android
- Added a convenience hook, `useOnEvent` , that
- is used by `useIsHeadphonesConnected`
- can be used to update existing event hooks to DRY them up
- can help 'simplify' future event hooks
=> adding useIsHeadphonesConnected

src/index.ts
re #1085
updates the following functions to use `getSupportedPlatformInfoFunctions(...)`
- `isPinOrFingerprintSet*`
- `getFontScale*`
- `getInstallerPackageName*`
- `getApiLevel*`
- `getBuildId*`
- `getUsedMemory*`
- able to confirm for iOS and android, but not windows
=> using getSupportedPlatformInfoFunctions

README.md
This PR updates the README to reflect the current implementation for the methods `getFreeDiskStorage`, `getTotalDiskCapacity`, `getFreeDiskStorageOld`, and `getTotalDiskCapacityOld`.
[v6.0.0](https://github.com/react-native-community/react-native-device-info/releases/tag/v6.0.0) changed the way `getFreeDiskStorage` and `getTotalDiskCapacity` were implemented for Android.
When the [PR](https://github.com/react-native-community/react-native-device-info/pull/1054) for this update was submitted, the new implementation of these methods was added with `*New` appended to the method names, which was how it was documented in the README.
Sometime between the PR and the release, the decision was made to allow this to be a breaking change, with the older implementations preserved by adding `*Old` to …
=> Update README getFreeDiskStorage and getTotalDiskCapacity

src/index.ts
re #1085
Updates the follow functions to use the helper function `getSupportedPlatformInfoFunctions`
- `getPowerState*`
- `getMaxMemory*`
- `getFirstInstallTime*`
- `getHardware*`
- `getDisplay*`
- `getBootloader*`
- `getManufacturer*`
- `isCameraPresent*`
- `getAndroidId*`
- `getInstanceId*`
- tested on iOS and Android, unable to do so on windows
=> using more `getSupportedPlatformInfoFunctions`

src/index.ts
Fixes #1085
Updates the following functions to use `getSupportedPlatformInfoFunctions`
- `getProduct*`
- `supported32BitAbis*`
- `getInstallReferrer*`
- `getIncremental*`
- `getSecurityPatch*`
- `getBaseOs*`
- `getTags*`
- `getHost*`
- `getFingerprint*`
- `getIpAddress*`
- `getSerialNumber*`
This should be all of the remaining conversions.
- tested on iOS and Android, but unable to do so on Windows
=> completing `getSupportedPlatformInfoFunctions` conversion

README.md, example/App.js, example/ios/Podfile, example/ios/Podfile.lock, example/ios/example-app-extension/ActionViewController.h, example/ios/example-app-extension/ActionViewController.m, example/ios/example-app-extension/Base.lproj/MainInterface.storyboard, example/ios/example-app-extension/Info.plist, example/ios/example-app-extension/Media.xcassets/Contents.json, example/ios/example-app-extension/Media.xcassets/TouchBarBezel.colorset/Contents.json, example/ios/example.xcodeproj/project.pbxproj, example/ios/example/ActionExtension.h, example/ios/example/ActionExtension.m, ios/RNDeviceInfo.xcodeproj/project.pbxproj, ios/RNDeviceInfo/RNDeviceInfo.m
Fixes #625
- updates how contentSize is obtained; using `[[UIScreen mainScreen] traitCollection];`
- updates example to include an app extension for testing and such **(MAJORITY OF THIS PR)**
BREAKING CHANGE: by obtaining the content size from `[[UIScreen mainScreen]
traitCollection].preferredContentSizeCategory` , this library drops support for iOS 9. This should
be fine since RN 0.63+ dropped support for iOS9 and the OS, itself, has <1% iOS market share.
=> supporting `getFontScale` in App Extensions

src/internal/supported-platform-info.ts
Object.fromEntries doesn't work in react-native-windows in release
builds or without the Web Debugger enabled.
Replace use of Object.fromEntries with equivalent code.
Fixes #1109
=> fix(windows): remove use of Object.fromEntries

.github/workflows/jest-test.yml, __tests__/async-hook-wrappers.test.ts, __tests__/getters.test.ts, babel.config.js, jest.config.js, jest.setup.ts, package.json, src/internal/asyncHookWrappers.ts, src/internal/supported-platform-info.ts, yarn.lock
re #1108
- sets up jest testing w/ GitHub Actions
- adds tests for `useOnMount` , `useOnEvent` , and `getInstanceId*`
- adds mocks
- exports `deviceInfoEmitter` used by `useOnEvent` (purely for testing)
- adds `clearMemo()` internal function
=> adding jest tests

__tests__/getters.test.ts, jest.setup.ts, src/internal/supported-platform-info.ts
re #1108
resolves  #1117
adds tests for the following groups of getters
- non-memoized boolean
- non-memoized number
- memoized array
- memoized boolean
- memoized number
fixes internal mock
- moves `getApiLevel` to `numberFnNames` (jest.setup.ts)
fixes a memoization bug related to falsy values in `getSupportedPlatformInfoFunctions`
<hr />
The `non-memoized string` are a bit more complicated ('tedious' is probably a better word), so I'll have that in a later PR, or hopefully, others can take on some. :)
=> more tests and a memoization bug fix

__tests__/getters.test.ts, jest.setup.ts, src/index.ts
re #1108
- updates some jest setup jazz
- add tests for:
- getManufacturer*
- getMacAddress*
- getIpAddress
- getPhoneNumber
- getCarrier
- getDeviceId
- getModel
- getBrand
- getSystemVersion
- getBundleId
- getApplicationName
- getBuildNumber
- getVersion
- getUniqueId
- getDeviceType
- getDeviceTypeSync
- getDeviceToken
- getSystemAvailableFeatures
- isTablet
- updates getter functions to have a smaller code base and to use global memo object (mainly for testing purposes)
- `getUniqueId`
- `getDeviceId`
- `getModel`
- `getBrand`
- `getSystemVersion`
- `getBundleId`
- `getApplicationName`
- `getBuildNumber`
- `getVersion`
- `isTablet`
- `getDeviceType`
- `getDeviceTypeSync`
| Windows |    ✅ …
=> Ensmallerizing more getters and adding more tests

CHANGELOG.md, README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, example/App.js, src/index.ts, src/internal/privateTypes.ts
Added `hasGms()` and `hasHms()` that tells you if the Android device supports Google Mobile Services or Huawei Managed Services.
=> Added hasGms and hasHms functions

jest/react-native-device-info-mock.js
adds what I believe to be the remaining mocks for all the functions of this lib
<hr />
@mikehardy this _should_ be it for mocks
=> feat(jest/react-native-device-info-mock): adding rest of mocks

jest/react-native-device-info-mock.js
Just stumbled upon the error below when trying to start tests using 7.2.0:
```
SyntaxError: node_modules/react-native-device-info/jest/react-native-device-info-mock.js: Unexpected token (105:38)
```
Seems a trailing `,` made it into the code.
Not required.
Not required.
=> Fix syntax error in mock definition

ios/RNDeviceInfo/RNDeviceInfo.m, src/index.js.flow, src/index.ts, src/internal/types.ts
As discussed here: https://github.com/react-native-device-info/react-native-device-info/issues/1127 and here: https://github.com/react-native-device-info/react-native-device-info/pull/1128
I've extended getDeviceType() to return "Desktop" on Catalyst and Windows apps. I'm not sure my solution for the windows version is desired, but it is tested and works.
=> Added DeviceTypeDesktop to getDeviceType()

CHANGELOG.md, package.json, src/index.ts, src/internal/asyncHookWrappers.ts, src/internal/privateTypes.ts
In this PR I am fixing the way typing are being imported and re-exported.
Fixes #1162
=> Fix import and export of types

ios/RNDeviceInfo/RNDeviceInfo.m
Expansion of PR #1137. That PR only checked if the app is an iOS app built for macOS not if it is an iOS app running on macOS. See https://developer.apple.com/documentation/xcode/creating_a_mac_version_of_your_ipad_app for details about how Catalyst is for creating a macOS native type package from an iOS app. #1137 uses a compile time define which is only present when creating a macOS version.
This adds a runtime check for running unmodified iOS apps on macOS, https://developer.apple.com/documentation/apple-silicon/running-your-ios-apps-on-macos . This allows proper detection of the underlying device type the iOS app is running on.
* [ X] I have tested this on a …
=> fix(ios, deviceType): support iOS-compiled app running on macOS

.github/workflows/jest-test.yml, .github/workflows/linting.yml, .github/workflows/tests_e2e.yml, .github/workflows/windows-app-test.yml
- default to node 14 mostly
- default to JDK11 now (will be minimum requirement next android gradle, move now)
=> chore(ci): update workflow actions

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Following the disussion in #1056 this will allow users of old MDM devices like the Sunmi V2 and others to access serial numbers via their privileged system access permissions assigned by the MDM.
This shouldn't cause any problems as the Build.SERIAL will be populated with 'unkown' regardless of permissions.
Been using this via patch-package for months with live Sunmi V2 devices. Works like a charm.
=> fix: get legacy serial number for old APIs (#1056)

.github/workflows/release.yml
Regarding the action, `Release` ,
replaces `GITHUB_TOKEN` environment variable w/ `GH_TOKEN` and updates the value to use the secret of the same name. `GITHUB_TOKEN` secret is a special secret that can't be set, so if you're writing into a protected branch, you'll need to add a PAT of a user that can write to said protected branches.
| iOS     |    N/A     |
-- 
_it sucks that there isn't a good way to test actions locally_
=> ci(.github/workflows/release.yml): using `GH_TOKEN` as env and secret

README.md, ios/RNDeviceInfo.xcodeproj/project.pbxproj, ios/RNDeviceInfo/EnvironmentUtil.h, ios/RNDeviceInfo/EnvironmentUtil.m, ios/RNDeviceInfo/RNDeviceInfo.m, src/index.ts
Related #1216
add `getCurrentAppEnvironment` function for ios to determine whether app was downloaded from `AppStore`,`TestFlight` or `Other`
=> Add getcurrentappenvironment

src/internal/devicesWithNotch.ts
[Pixel 3a](https://i.pcmag.com/imagery/reviews/01bJFrj1Us02CAmWTJAD9oe-21.1569474132.fit_scale.size_1028x578.jpg) does not have a notch.
=> Remove `pixel 3a` from devicesWithNotch.ts

src/web/index.js
Add a check to see if navigator is defined. This fixes server side rendering in node where navigator is not defined. Since init is called when the module is required this causes an issue, even if not using any of the library methods.
web only fix
=> Fix init if navigator is not defined

android/build.gradle, android/gradle.properties
Android Gradle Plugin 4.2 ignore submodule gradle.properties, so this file is unused
remove it - tested it via removing it from the installed location in
node_modules/react-native-device-info/android/gradle.properties and it
was fine
| iOS     |         |
| Windows |        |
=> build(android): gradle plugin 4.2 ignores submodule gradle.properties

.github/workflows/tests_e2e.yml, example/ios/Podfile.lock, package.json
No issue logged - just integrating https://github.com/mikehardy/buildcache-action to speed things up in CI
I tested this on a machine that did not have buildcache installed via `yarn example:ios:build` to make sure it was backwards-compatible, it is
| Android |         |
| Windows |        |
=> test(e2e, ios): buildcache-action for faster ios build

README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
My company is logging some metrics around memory usage and we've found there is a large discrepancy between iOS and Android. Android is about an order of magnitude lower. 
This is more inline with what's happening in iOS. Android was previously only getting the used bytes from the RN Runtime,
not the entire app.
The Android example app went from reporting ~4mb => ~80mb which is way more inline with what I'd expect.
**Do I need to bump the version in package json or will you take care of that on the next release?**
Fixes #895 
Some of the checklist items don't apply since I didn't change any APIs.
=> fix: make getUsedMemory more inline with iOS #895

CHANGELOG.md, src/internal/devicesWithNotch.ts
Fixes #1275
Add Redmi Note 8 Pro to the list of devices with notch
| Android |    ✅   |
=> fix(hasNotch): add Redmi Note 8 Pro to hasNotch list

windows/RNDeviceInfoCPP/RNDeviceInfoCPP.vcxproj, windows/RNDeviceInfoCPP61/RNDeviceInfoCPP61.vcxproj
Fixes #1278
Replace macro of msbuild in project file.
=> fix(windows): react-native-device-info don't work with apps in RNW v0.64

README.md
this PR add links to redirect links netinfo and network info library, like description say "deprecated method" i think it's a good idea redirect this libraries
> ## Checklist
> * [ ]  I have tested this on a device/simulator for each compatible OS
> * [x]  I added the documentation in `README.md`
> * [ ]  I updated the typings files (`privateTypes.ts`, `types.ts`)
> * [ ]  I added a sample use of the API (`example/App.js`)
=> docs: add links for ipAdress deprecated

src/internal/devicesWithNotch.ts
iPhone 13 lineup is about a week out, so adding this to the device list for devices with notch.
=> fix(hasNotch): Add iPhone 13 lineup to list of devices with notch

ios/RNDeviceInfo/RNDeviceInfo.m
Adds missing device name by code for iPhone 13 lineup. Relates to #1307
=> fix(hasNotch): Missing device name for iPhone 13

CODEOWNERS, package.json
adds myself to `CODEOWNER` — I think this is how one automatically get assigned to review PRs. I don't get assigned/notified, so I don't see them.
| iOS     |    N/A     |
=> docs: adding @schie as a contributor / code owner

ios/RNDeviceInfo/RNDeviceInfo.m
removes added stubs to allow NativeEventEmitter to work on iOS again
resolves #1301
- tested on iOS and Android.
- tested on RN 0.64 and 0.65
=> revert(ios/rndeviceinfo): removing ios listener stubs

RNDeviceInfo.podspec, example/README.md, example/package.json, refresh-example.sh, src/internal/nativeInterface.ts
- fix(internal/nativeinferface): fixing exception message when RNDeviceInfo is not found
- fix(rndeviceinfo.podspec): changing podspec git source
- docs(example): replacing usage of `react-native-community`
- chore(refresh-example): replacing old org
replaces more usage of `react-native-community/react-native-device-info` with current org. This should be the rest of it.
=> fix: replacing react native community

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
For some reason on targetSdkVersion30+ in some cases, you can have the appropriate
permission but still take a SecurityException when you attempt to call getLine1Number
This allows the method to gracefully fallback to "unknown" instead of crashing
This tested directly in an app I'm working on, I can reproduce a crash every time even though
when I probe it, I appear to have READ_SMS permission, right before I get a SecurityException saying...I don't have READ_SMS permission? It's quite odd.
=> fix(android): gracefully handle SecurityException in getPhoneNumber

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixes #1320
Nothing this is a minor fix ...
=> fix(android, serial): Fix permission access to serial number

src/index.ts
Fixes [#1346](https://github.com/react-native-device-info/react-native-device-info/issues/1346)
The hook `useBatteryIsLow` returns the current battery level on initial rendering - even if the current battery level is not considered as low (Android < 0.15, iOS < 0.20);
With removing the initial value from the useEffect hook on initial rendering, the returned value remains `null` until the listener `RNDeviceInfo_batteryLevelIsLow`  detects the first callback for a low battery status.
On iOS simulator the battery level is always `-1`.
On Android emulator the battery level is always `1`.
At least for me.
I therefore tested it on an external physical device too. See the video in the linked ticket above. 
I did not find dedicated tests for the hooks. Let me know if I missed something.
| OS …
=> fix(useBatteryIsLow): return battery level only if low

README.md
Fixes #1358
Since iPadOS 15.0 (or iOS 15.0) iPads return "iPadOS" as the system name.
I've added a line in docs that states that.
=> docs: Add possible ipados return value for getSystemName

.github/workflows/release.yml, .github/workflows/stale.yml
`release.yml` runs on push to master, and `stale.yml` runs on schedule. Both workflows should **not be run on forked repositories**. The credentials and permissions are missing, resulting in tons of failed runs (including email notifications):
> [fork/react-native-device-info] Run failed: Mark stale issues and pull requests - master (808c1b5)
=> ci: Do not run release and stale flows on forks

.github/workflows/stale.yml
Use a different way to check if the `stale` workflow was started in a forked repo.
It turned out the check added in #1361 does not work as expected for workflows with a `schedule` trigger.
The solution is described in this thread:
https://github.community/t/github-event-repository-fork-context-does-detect-forks-in-scheduled-jobs/185925/3
=> Update stale workflow fork check

README.md, src/index.ts, src/internal/supported-platform-info.ts, windows/code/RNDeviceInfoCPP.h
Added the getSupportedAbis methods for windows which allows a user to grab a windows device's current supported CPU architectures including x86, x64, and arm.
=> feat(windows, supportedAbis): Add supportedAbis for windows

ios/RNDeviceInfo/RNDeviceInfo.m
Adds missing device name by code for iPhone SE 3rd gen
=> fix(ios): Missing device name for iPhone SE 3rd gen

README.md, example/App.js, example/ios/Podfile.lock, ios/RNDeviceInfo/RNDeviceInfo.m, jest/react-native-device-info-mock.js, src/index.js.flow, src/index.ts, src/internal/privateTypes.ts
Added `getBrightness()` support for iOS to get the current brightness level of the device's main screen.
**Device test screenshot:**
=> feat(ios): add getBrightness support for iOS

windows/code/RNDeviceInfoCPP.h
Doing windows equivalent for
https://github.com/react-native-device-info/react-native-device-info/pull/1289
https://github.com/react-native-device-info/react-native-device-info/issues/1288
https://github.com/react-native-device-info/react-native-device-info/commit/c518c32202c7af548ffd4bd797662d9493fed3bf
Fixes #1288
=> fix(windows): addListener/removeListeners native stubs to quiet warnings

README.md, example/App.js, ios/RNDeviceInfo/RNDeviceInfo.m, src/index.js.flow, src/index.ts, src/internal/devicesWithDynamicIsland.ts, src/internal/devicesWithNotch.ts, src/internal/privateTypes.ts
- Added device names for new iPhone 14 family and updated `hasNotch` device list
- Added `hasDynamicIsland()` that allows to check if device has a [Dynamic Island](https://www.youtube.com/watch?v=WuEH265pUy4)
=> feat: Add device names for iPhone 14 family,  add check for dynamic island

README.md
`getUserAgent` and `getUserAgentSync` have different platform support; as they have the same name, this creates confusion among the developers using the library. To avoid that a note has been added to the readme. Fixes #985
=> docs(README): note getUserAgentSync is only available on android

src/internal/devicesWithNotch.ts
Add iPhone 14 Pro / iPhone 14 Pro Max to devices with notch
* [ X] I have tested this on a device/simulator for each compatible OS
=> fix(hasNotch): add iPhone 14 Pro / Pro Max to devices with notch

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixes #1463
This fixes devices targeting API 32 or 33 from always returning 'unknown' due to an exception when fetching the bluetooth name.
* [N/A] I added the documentation in `README.md`
* [N/A] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [N/A] I added a sample use of the API (`example/App.js`)
=> Fixes getDeviceName on Android when targeting API level 32 or newer

README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, android/src/main/java/com/learnium/RNDeviceInfo/resolver/DeviceIdResolver.java, example/android/build.gradle, refresh-example.sh
firebase IID and GMS IID are both long long deprecated and problematic now
We need to drop them but if anyone happens to be relying on them they will need to maintain
the current value
So start in this version by saving current values to shared preferences for stability
If Firebase IID and GMS IID are not available, start generating a UUIDv4 instance ID and saving it
=> feat(android, instanceId): implement as UUIDv4 in shared prefs, w/fallback

src/index.ts
Fixes `getUserAgent` returning `unknown` when used with the `getUserAgentSync`
For example,
```javascript
let userAgent = '' + Platform.select({
android: DeviceInfo.getUserAgentSync(), // sync not supported by iOS - supportedPlatforms: ['android', 'web']
default: await DeviceInfo.getUserAgent(),
})
```
On `ios` it will return `unknown`
**The reason:**
`getUserAgent` and `getUserAgent` have same `memoKey`
https://github.com/react-native-device-info/react-native-device-info/blob/master/src/index.ts#L228
https://github.com/react-native-device-info/react-native-device-info/blob/master/src/index.ts#L236
=> getUserAgentSync: fix memoKey

README.md, example/App.js, ios/RNDeviceInfo/RNDeviceInfo.m, src/index.js.flow, src/index.ts, src/internal/privateTypes.ts
add feat to check if the app has the zoomed feature enabled only for ios
Fixes #1485
Added `isDisplayZoomed()` that allows to check if the user has enabled the `zoomed` feature from IOS
=> feat: add DisplayZoomed ios

jest/react-native-device-info-mock.js
Adds missing mock with the following config
```
import mockRNDeviceInfo from 'react-native-device-info/jest/react-native-device-info-mock';
jest.mock('react-native-device-info', () => mockRNDeviceInfo);
```
=> fix: add missing mock

windows/RNDeviceInfoCPP/RNDeviceInfoCPP.vcxproj
In RNW .72, we bump WinUI from 2.7 to 2.8 which targets a higher TargetPlatformMinVersion. This PR bumps the WindowsTargetPlatformMinVersion to the correct version for RNW .72
| iOS     |    N/A     |
| Android |    N/A      |
=> fix(windows): bump WindowsTargetPlatformMinVersion

README.md
getDeviceName only returns generic value unless app is given explicit entitlements to access user-defined device name.
Fixes [#1516](https://github.com/react-native-device-info/react-native-device-info/issues/1516)
=> docs: Update README.md for getDeviceName

README.md, example/App.js, src/index.js.flow, src/index.ts, src/internal/privateTypes.ts, windows/code/RNDeviceInfoCPP.h
Added windows implementation of getHostNames(). Using this user can get all host names of windows devices.
Fixes #1564 
| -------  | :---------: |
| Windows |    ✅  |
=> feat(windows): Implemented getHostNames() for windows

README.md
On latest version (10.11.0) `usePowerState` and the listener both return a power state object, as opposed to just the battery state (e.g. 'charging')
* Fixes react-native-device-info/react-native-device-info#1587
=> docs: Update README documentation for `usePowerState`

README.md
In order to avoid Null Pointer Exception
When using this package with ProGuard enabled, on start-up of the app it crashes with the following error
```
java.lang.NullPointerException
at com.android.installreferrer.api.b$b.onServiceConnected(SourceFile:24)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2207)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2240)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8248)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.j …
```
=> docs(README): update README for proguard rule

src/internal/asyncHookWrappers.ts
Since `useOnEvent` returns an object which gets recreated on every render, this makes the value returned unstable and cause bug by retriggering useEffects when the value did not really change.
Assume the following:
```
import {useEffect, useState} from 'react';
import {useIsHeadphonesConnected} from 'react-native-device-info';
function App() {
const isHeadphonesConnected = useIsHeadphonesConnected();
const [_, setCounter] = useState(0);
useEffect(() => {
const intervalId = setInterval(() => {
setCounter(prev => prev + 1);
}, 1000);
return () => {
clearInterval(intervalId);
};
}, []);
useEffect(() => {
// some intensive work
console.log('isHeadphonesConnected', isHeadphonesConnected);
}, [isHeadphonesConnected]);
return null;
}
export default App;
```
Since `useIsHeadphonesConnected` uses …
=> fix: wrap return value of useOnEvent in useMemo

README.md, RNDeviceInfo.podspec, ios/RNDeviceInfo/RNDeviceInfo.m
Added `visionOS` platform support for the library.
<details>
<summary>1. Constant</summary>
</details>
<details>
<summary>2. Sync</summary>
</details>
<details>
<summary>3. Async</summary>
</details>
<details>
<summary>4. Hooks</summary>
</details>
- [Bringing React Native libraries to Apple Vision Pro](https://www.oskarkwasniewski.dev/blog/bringing-react-native-libraries-to-apple-vision-pro)
- https://callstack.github.io/react-native-visionos-docs/
=> feat: add visionos platform support

ios/RNDeviceInfo/RNDeviceInfo.m
@UNIDY2002 raised a build failing issue [here](https://github.com/react-native-device-info/react-native-device-info/pull/1614#issuecomment-1962225526) due to visionos changes introduced by #1614.
I could also see same error in our github action ios build logs [here](https://github.com/react-native-device-info/react-native-device-info/actions/runs/8021357309/job/21913661609#step:12:299).
After referring to https://github.com/facebook/react-native/pull/42243/files#diff-ec1473a9d036148f566ce45864dfa02def7a9edc156862c9ea1ff8f374b59087 , I've added similar guardrail for our lib.
[`UIUserInterfaceIdiomVision`](https://developer.apple.com/documentation/uikit/uiuserinterfaceidiom/uiuserinterfaceidiomvision) is available only for iOS 17.0+.
=> fix(getDeviceType): add TARGET_OS_VISION guard for UIUserInterfaceIdiomVision

RNDeviceInfo.podspec, ios/PrivacyInfo.xcprivacy, ios/RNDeviceInfo.xcodeproj/project.pbxproj
Added a privacy manifest file to comply with Apple's upcoming [privacy manifest requirements](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files). 
Changes were based off Apple's documentation for [describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api).
Added values for the following APIs used by the lib:
- NSFileCreationDate
- NSFileSystemFreeSize
- NSFileSystemSize
- NSUserDefaults
Let me know if there's any changes that need to be made.
Fixes #1622 
| Android |    n/a     |
| Windows |    n/a     |
=> fix(ios): add Apple privacy manifest

android/build.gradle, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, example/android/build.gradle
Targeting Android 14 requires the specification of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED when registering a receiver. Docs: https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported
using CompatConext allow us to avoid the android version check as it handles it internally
* [n/a (Only android) ] I have tested this on a device/simulator for each compatible OS
* [ n/a] I added the documentation in `README.md`
* [ n/a] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ n/a] I added a sample use of the API (`example/App.js`)
=> feat(android)!: targetSdk 34 requires receiver export specification during registration

README.md, __tests__/getters.test.ts, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, example/App.js, jest.setup.ts, jest/react-native-device-info-mock.js, src/index.js.flow, src/index.ts, src/internal/privateTypes.ts
Fixes #1612 
The getPhoneNumber() method has been removed. Because this method uses deprecated getLine1Number function. It is recommended to use alternative methods to get phone numbers from SIM cards.  You can use https://github.com/odemolliens/react-native-sim-cards-manager instead.
=> fix(android)!: removed deprecated getPhoneNumber - use react-native-sim-cards-manager if needed

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixes #1602
This change allows the MEmu Play emulator to be detected in the `isEmulator()` function.
=> feat(android): Added MEmu emulator check in isEmulator function

ios/RNDeviceInfo/RNDeviceInfo.m
Fixes #1581.
On iPhone 12 mini and iPhone 13 mini, `isDisplayZoomed()` always returns true, independent of whether `Display & Brightness` -> `Display Zoom` is enabled.
We fix this issue by changing the comparison operator (see [here](https://stackoverflow.com/a/65844985)).
=> fix(ios): isDisplayZoomed on iPhone 12/13 mini

ios/RNDeviceInfo/RNDeviceInfo.m, src/internal/devicesWithDynamicIsland.ts, src/internal/devicesWithNotch.ts
Added iPhone 16 support for notch and dynamic island. 
Devices codes picked from: https://gist.github.com/adamawolf/3048717
Fixes #1541
Supercedes #1619
=> feat(ios): add iPhone 16 device names / add missing iPad device names

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Fixes #1651
I expected the `usePowerState` or `RNDeviceInfo_powerStateDidChange` to return a `powerState` :object, but it was only returning an object at first and then only the `batteryState` value afterwards.
I have modified it to always return an object.
According to the documentation, it is supposed to return a `powerState` object, so I made functional changes without modifying the documentation.
=> fix(android)!: powerStateDidChange returns full powerState object not batteryState value

README.md
Just a missing parenthesis that could mislead someone who is distracted
=> docs(README): typo fix in sample code

README.md, example/App.js, ios/RNDeviceInfo/RNDeviceInfo.m, package.json, src/index.ts, src/internal/privateTypes.ts, src/internal/supported-platform-info.ts, src/internal/types.ts, src/web/index.js
Fixes #1148
This issue has been closed, but no action has been taken afaik. 
Please let me know if you want me to open a new issue. 
Apple's suggestion on how to get storage capacity: https://developer.apple.com/documentation/foundation/urlresourcekey/checking_volume_storage_capacity
* [ X] I have tested this on a device/simulator for each compatible OS (note: I have only tested on iOS version 11+)
* [ NA] I added the documentation in `README.md` 
* [ NA] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [NA] I added a sample use of the API (`example/App.js`)
=> feat(ios): implement all free disk storage types for ios 11+

.github/workflows/tests_e2e.yml
there is an interaction with other env vars defined on ubuntu-24 runner image that were not on ubuntu-22 that makes the avd create in an unwnanted directory
Simply defining the env vars may be sufficient, or I may need to create /home/runner/.android/avd directory as well, we will see
=> test(ci): define env vars needed by ubuntu-24 image

README.md, android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, example/App.js, ios/RNDeviceInfo/RNDeviceInfo.m, jest/react-native-device-info-mock.js, src/index.ts, src/internal/privateTypes.ts
Added `getStartupTime()` that allows getting the startup time of the app in milliseconds since the unix epoch. 
This can for example be used to measure the time since app launch via `new Date().getTime() - getStartupTimeSync()`.
=> feat: add getStartupTime

CHANGELOG.md
The breaking change is currently written as affecting [`getDeviceId`](https://github.com/react-native-device-info/react-native-device-info?tab=readme-ov-file#getdeviceid) but it doesn't. [`getInstanceId`](https://github.com/react-native-device-info/react-native-device-info?tab=readme-ov-file#getinstanceid) is the affected method.
This is a documentation mistake in the `CHANGELOG.md` file originating from the change made in #1673. The [releases page](https://github.com/react-native-device-info/react-native-device-info/releases) also needs to be corrected but I don't have edit permission for that. Fixing this prevents developers from wasting their time and making a mistake auditing usage of the wrong method.
=> docs: Fix incorrect method referred to for v14.0.0

README.md, windows/code/RNDeviceInfoCPP.h
Updated Windows-on-ARM CPU architecture types for Windows in the existing `getSupportedAbis` API as per https://learn.microsoft.com/en-us/uwp/api/windows.system.processorarchitecture?view=winrt-26100#fields
=> fix(windows): Update RNDeviceInfoCPP.h for windows on ARM CPU arch on windows

ios/RNDeviceInfo/RNDeviceInfo.m
- Fixes #1670. Apis are [not available for tvos](https://developer.apple.com/documentation/foundation/urlresourcekey/checking_volume_storage_capacity).
- Fixes compilation issue: `sysctl` needs to be imported for tvos as well.
=> fix(tvos): Fix compilation issues due to missing apis in keyForStorageType for tvos (#1670)

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java, example/ios/Podfile.lock
the minSdk for supported versions of react-native will be 24 once react-native 0.78 ships, but there is no reason not to maintain compatibility with 23 right now
however, the API the process uptime feature depends on doesn't exist before then so just return our "undefined" numeric value of -1
Fixes unlogged issue but noticed it when I went to upgrade react-native-firebase, which depends on this module but has minSdk 23 *and* a NewAPI lint check (which apparently we don't have here so we didn't catch it...)
=> fix(android): restore compatibility for Android <= 23

android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
we already handle the onCatalystInstanceDestroy method deprecation pretty well, but we get build warnings for even keeping the old API, though we do that on purpose for backwards-compatibility
So suppress those build warnings since they look worrisome but are not actionable
There was one poster that mentioned it, and I noticed it as well in my own usage of the module:
- Fixes #1689
I checked compiling this against a really old react-native (the example here being so out of date actually helped! CI will show it as well) and I tested it against a modern react-native where the warning was generated. Both still worked, so I think this is backwards- and forwards-compatible
=> fix(android): quiet a build warning for users
